<a href="https://colab.research.google.com/github/Meenakshimadhu192001/Case_study/blob/main/Casestudy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###importing Libraries

In [ ]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
file_path = '/content/adult_dataset (1).csv'
df = pd.read_csv('/content/adult_dataset (1).csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39.0,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40.0,NaN,<=50K
1,50.0,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13.0,United-States,<=50K
2,38.0,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40.0,United-States,<=50K
3,53.0,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40.0,United-States,<=50K
4,28.0,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40.0,Cuba,<=50K

In [ ]:
df.shape

(48842, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             46400 non-null  float64
 1   workclass       45480 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      45485 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  46400 non-null  float64
 13  native-country  46137 non-null  object
 14  income          48842 non-null  object
dtypes: float64(2), int64(4), object(9)
memory usage: 5.6+ MB

In [ ]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,46400.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,46400.000000
mean,38.679116,1.896641e+05,10.078089,1079.067626,87.502314,40.448599
std,13.952954,1.056040e+05,2.570973,7452.019058,403.004552,12.646992
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,255.000000,1.490400e+06,16.000000,99999.000000,4356.000000,250.000000

###Check Missing Values

In [ ]:
df.isnull().sum()

age               2442
workclass         3362
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        3357
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week    2442
native-country    2705
income               0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(16)

In [ ]:
# Cell C: handle missing values (THIS MUST COME BEFORE ENCODING)
df['income'] = df['income'].str.replace('.', '', regex=False)
df.replace('?', np.nan, inplace=True)
df.dropna(inplace=True)

print(df.isnull().sum().sum())
print(df['income'].unique())

0
['<=50K' '>50K']

In [ ]:
df.drop_duplicates(inplace=True)

###Encoding

In [ ]:
cat_cols = df.select_dtypes(include='object').columns

print(cat_cols)

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country', 'income'],
      dtype='object')

In [ ]:

cat_cols = df.select_dtypes(include='object').columns
le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [ ]:
le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [ ]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
1,50.0,4,83311,9,13,2,3,0,4,1,0,0,13.0,38,0
2,38.0,2,215646,11,9,0,5,1,4,1,0,0,40.0,38,0
3,53.0,2,234721,1,7,2,5,0,2,1,0,0,40.0,38,0
4,28.0,2,338409,9,13,2,9,5,2,0,0,0,40.0,4,0
5,37.0,2,284582,12,14,2,3,5,4,0,0,0,40.0,38,0

###Split Features and Target

In [ ]:
#splitting to target and features
y=df['income']            #target
x=df.drop(columns=['income'],axis=1) #features
#splitting into test train data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=33)

###scaling

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [ ]:
# TensorFlow model
tf_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(x_train.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
tf_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
start_time = time.perf_counter()
history = tf_model.fit(x_train, y_train, epochs=50, batch_size=32,
                        validation_split=0.2, verbose=1)
end_time = time.perf_counter()
print(f"Training Time: {end_time - start_time:.4f} seconds")

Epoch 1/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.6735 - loss: 388.8636 - val_accuracy: 0.7901 - val_loss: 76.7339
Epoch 2/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6776 - loss: 203.0139 - val_accuracy: 0.7777 - val_loss: 38.9654
Epoch 3/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.6746 - loss: 115.8801 - val_accuracy: 0.7654 - val_loss: 321.8513
Epoch 4/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6777 - loss: 143.8745 - val_accuracy: 0.7858 - val_loss: 230.5508
Epoch 5/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6786 - loss: 119.0187 - val_accuracy: 0.7851 - val_loss: 128.5663
Epoch 6/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6789 - loss: 121.7286 - val_accuracy: 0.7836 - val_loss: 36.9481
Epoch 7/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6854 - loss: 70.3586 - val_accuracy: 0.7799 - val_loss: 19.5968
Epoch 8/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6818 - loss: 83.9242 - val_accuracy: 0.3675 - val_loss: 19.0621
Epoch 9/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6815 - loss: 50.5604 - val_accuracy: 0.7817 - val_loss: 65.6635
Epoch 10/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6822 - loss: 63.8801 - val_accuracy: 0.7797 - val_loss: 51.7362
Epoch 11/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6832 - loss: 67.7765 - val_accuracy: 0.7740 - val_loss: 150.6110
Epoch 12/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6822 - loss: 68.1973 - val_accuracy: 0.7901 - val_loss: 26.4452
Epoch 13/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6796 - loss: 53.5424 - val_accuracy: 0.7927 - val_loss: 29.2899
Epoch 14/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6801 - loss: 46.5470 - val_accuracy: 0.2505 - val_loss: 89.2122
Epoch 15/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6841 - loss: 40.0931 - val_accuracy: 0.7427 - val_loss: 8.2988
Epoch 16/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6805 - loss: 43.2279 - val_accuracy: 0.7775 - val_loss: 13.5274
Epoch 17/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6881 - loss: 25.6827 - val_accuracy: 0.7600 - val_loss: 47.6181
Epoch 18/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6858 - loss: 35.0240 - val_accuracy: 0.2588 - val_loss: 52.4727
Epoch 19/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6851 - loss: 31.8976 - val_accuracy: 0.7690 - val_loss: 23.6980
Epoch 20/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6921 - loss: 24.7203 - val_accuracy: 0.7725 - val_loss: 70.4878
Epoch 21/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6899 - loss: 24.7127 - val_accuracy: 0.7936 - val_loss: 23.7330
Epoch 22/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6922 - loss: 28.3598 - val_accuracy: 0.7918 - val_loss: 18.7836
Epoch 23/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6896 - loss: 25.1739 - val_accuracy: 0.7920 - val_loss: 22.3231
Epoch 24/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6960 - loss: 20.3570 - val_accuracy: 0.2668 - val_loss: 38.6418
Epoch 25/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6920 - loss: 23.8129 - val_accuracy: 0.5027 - val_loss: 7.2983
Epoch 26/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6882 - loss: 19.6225 - val_accuracy: 0.2595 - val_loss: 41.2318
Epoch 27/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6911 - loss: 17.6523 - val_accuracy: 0.7942 - val_loss: 13.7095
Epoch 28/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6967 - loss: 14.9266 - val_accuracy: 0.7865 - val_loss: 5.5434
Epoch 29/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6971 - loss: 12.6376 - val_accuracy: 0.7913 - val_loss: 12.2385
Epoch 30/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7006 - loss: 11.7027 - val_accuracy: 0.7820 - val_loss: 5.3606
Epoch 31/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6971 - loss: 8.3014 - val_accuracy: 0.2697 - val_loss: 26.3626
Epoch 32/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7087 - loss: 8.9405 - val_accuracy: 0.7899 - val_loss: 4.5996
Epoch 33/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7001 - loss: 9.9316 - val_accuracy: 0.7940 - val_loss: 5.1630
Epoch 34/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7132 - loss: 6.1827 - val_accuracy: 0.7852 - val_loss: 6.4364
Epoch 35/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7041 - loss: 7.8358 - val_accuracy: 0.7899 - val_loss: 2.6535
Epoch 36/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7064 - loss: 7.2236 - val_accuracy: 0.7913 - val_loss: 2.4899
Epoch 37/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7097 - loss: 6.6811 - val_accuracy: 0.7831 - val_loss: 6.9696
Epoch 38/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7068 - loss: 7.3263 - val_accuracy: 0.7879 - val_loss: 3.0037
Epoch 39/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7055 - loss: 7.4856 - val_accuracy: 0.7774 - val_loss: 17.1742
Epoch 40/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7156 - loss: 5.6366 - val_accuracy: 0.6132 - val_loss: 3.0547
Epoch 41/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7132 - loss: 5.8012 - val_accuracy: 0.7690 - val_loss: 1.1564
Epoch 42/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7091 - loss: 5.1772 - val_accuracy: 0.7679 - val_loss: 1.9525
Epoch 43/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7153 - loss: 4.9068 - val_accuracy: 0.6402 - val_loss: 1.7521
Epoch 44/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7093 - loss: 4.8610 - val_accuracy: 0.7888 - val_loss: 5.5526
Epoch 45/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7167 - loss: 4.7676 - val_accuracy: 0.7622 - val_loss: 0.9947
Epoch 46/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7171 - loss: 3.3677 - val_accuracy: 0.3593 - val_loss: 6.5515
Epoch 47/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7225 - loss: 3.3775 - val_accuracy: 0.4056 - val_loss: 4.8482
Epoch 48/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7151 - loss: 4.0289 - val_accuracy: 0.7729 - val_loss: 0.8967
Epoch 49/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7241 - loss: 2.5078 - val_accuracy: 0.7924 - val_loss: 1.2182
Epoch 50/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7170 - loss: 3.4149 - val_accuracy: 0.3206 - val_loss: 7.1784
Training Time: 111.0584 seconds

In [ ]:
loss, accuracy = tf_model.evaluate(x_test, y_test)
print("accuracy:", accuracy)

219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3256 - loss: 7.3257
accuracy: 0.3256080150604248

##PyTorch

In [ ]:
# Cell 22 correction
x_train_tensor = torch.FloatTensor(X_train)
x_test_tensor = torch.FloatTensor(X_test)
y_train_tensor = torch.FloatTensor(y_train.values.reshape(-1,1))
y_test_tensor = torch.FloatTensor(y_test.values.reshape(-1,1))

In [ ]:
import torch
import torch.nn as nn

class ANN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network(x)

In [ ]:
model = ANN(input_dim=x_train_tensor.shape[1])

In [ ]:
criterion = nn.BCELoss()

In [ ]:
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [ ]:
start_time = time.perf_counter()
epochs = 50
for epoch in range(epochs):
  outputs = model(x_train_tensor)
  loss = criterion(outputs, y_train_tensor)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if (epoch+1) % 10 == 0:
    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')
end_time = time.perf_counter()
print(f"Training time: {end_time-start_time:.4f}seconds")

Epoch [10/50], Loss: 0.6519
Epoch [20/50], Loss: 0.5902
Epoch [30/50], Loss: 0.5366
Epoch [40/50], Loss: 0.4908
Epoch [50/50], Loss: 0.4526
Training time: 1.3882seconds